#!/bin/bash

#########################################
#
# This script just runs the Django self-
# -hosted development web server on the
# first available port from 8080 upwards.
#
# This variant will generate a new private
# key and self-sign a ssl certificate using
# that key.
#
# These should NOT be used for production use!!!
#
#########################################

cd dldb && ./manage.py runserver_plus --cert-file cert.crt --reloader-interval 5
cd -
